name: first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: List and Read file
        run: |
          echo "My first GH Actions Job jk"
          ls -ltra
          cat README.md

      - name: Generate ACII artwork
        run: cowsay -f dragon "Run for cover, I am dragon... rawr" >> dagon.txt

      #- name: list files
      #  run: ls

      #- name: read file
      #  run: cat README.md
